name: Create release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          body: | 
            Changes in the release
            - First Change
            - Second Change
          draft: true
          prerelease: false
