language: node_js
node_js:
  - "10"
  - "12"
deploy:
  provider: script
  script: "npm publish"
notifications:
  email:
    recipients:
      - dev.ciao@sylin.me
    on_success: change
    on_failure: always
